add missing thrust headers
Building with GCC 15.2.1 against CUDA 13.2.1 (CMake reports to have found
CUDAToolkit version 13.2.78) would yield these errors:

- viskores/viskores/exec/cuda/internal/ExecutionPolicy.h(185): error: namespace "thrust" has no member "pair"
  __attribute__((host)) __attribute__((device))::thrust::pair<OutputIterator1, OutputIterator2> reduce_by_key(

- viskores/viskores/cont/cuda/internal/DeviceAdapterAlgorithmCuda.h(721): error: namespace "thrust" has no member "pair"
      ::thrust::pair<decltype(keys_out_begin), decltype(values_out_begin)> result_iterators;
- viskores/viskores/cont/cuda/internal/DeviceAdapterAlgorithmCuda.h(745): error: namespace "thrust" has no member "distance"
      return static_cast<viskores::Id>(::thrust::distance(keys_out_begin, result_iterators.first));

Adding <thrust/pair.hpp> and <thrust/distance.hpp> fixes this.